name: release
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  rust:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: ${{ github.ref == 'refs/heads/main' && 'release' || '' }}
    defaults:
      run:
        working-directory: vm/rust
    steps:
      - uses: actions/checkout@v5
      - uses: raviqqe/cargo-cache@v1
      - run: cargo install cargo-workspaces
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo workspaces publish -y --from-git ${{ github.ref != 'refs/heads/main' && '--dry-run' || '' }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  release:
    needs:
      - rust
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
