name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  rust:
    strategy:
      fail-fast: false
      matrix:
        options:
          -
          - --all-features
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vm/rust
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: raviqqe/cargo-cache@4c7db86c0f73cc94a5608ad8b09e7a8e136fd259 # v1.0.4
      - run: cargo build ${{ matrix.options }}
      - run: cargo fmt -- --check
      - run: cargo clippy ${{ matrix.options }} -- -D warnings
      - run: cargo test ${{ matrix.options }}
  test:
    needs:
      - rust
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
