name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  rust:
    strategy:
      fail-fast: false
      matrix:
        features:
          - i32
          - i64
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vm/rust
    steps:
      - uses: actions/checkout@v5
      - uses: raviqqe/cargo-cache@v1
      - run: cargo build --features ${{ matrix.features }}
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings --features ${{ matrix.features }}
      - run: cargo test --features ${{ matrix.features }}
  test:
    needs:
      - rust
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
