name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  rust:
    strategy:
      fail-fast: false
      matrix:
        options:
          -
          - --all-features
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vm/rust
    steps:
      - uses: actions/checkout@v5
      - uses: raviqqe/cargo-cache@v1
      - run: cargo build ${{ matrix.options }}
      - run: cargo fmt -- --check
      - run: cargo clippy ${{ matrix.options }} -- -D warnings
      - run: cargo test ${{ matrix.options }}
  test:
    needs:
      - rust
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
